version: "3"

tasks:
  dev:
    desc: Start Dagster development server
    cmds:
      - uv run dg dev

  test:
    desc: Run tests with detailed tracebacks
    cmds:
      - uv run pytest --tb=long

  clean:
    desc: Clean temporary files, caches, and local run data
    cmds:
      - rm -rf .pytest_cache .ruff_cache .mypy_cache .coverage htmlcov site/ local_runs/ tmp*.db

  docs:
    desc: Start MkDocs development server
    cmds:
      - uv run mkdocs serve

  lint:
    desc: Run ruff linter and formatter checks
    cmds:
      - uv run ruff check .
      - uv run ruff format --check .
      - uv run mypy src --extra-checks

  build:
    desc: Run Podman build and tag the image
    cmds:
      - podman build -t ghcr.io/arookieds/dagster-code-location-crypto-data:latest .

  build-run:
    desc: Run Podman build, tag the image, and runs it
    cmds:
      - task: build
      - podman run --rm -p 3000:3000 ghcr.io/arookieds/dagster-code-location-crypto-data:latest

  run:
    desc: Run Podman run on the built image
    cmds:
      - podman run --rm -p 3000:3000 ghcr.io/arookieds/dagster-code-location-crypto-data:latest

  validate:
    desc: Validate Dagster definitions
    cmds:
      - uv run dg check defs

  default:
    desc: Run linting and tests (pre-flight check)
    cmds:
      - task: lint
      - task: test
