version: "3"

vars:
  ENV: LOCAL

tasks:
  dev:
    desc: Start Dagster development server
    cmds:
      - uv run dg dev

  test:
    desc: Run tests with detailed tracebacks
    cmds:
      - uv run pytest --tb=long

  clean:
    desc: Clean temporary files, caches, and local run data
    cmds:
      - rm -rf .pytest_cache .ruff_cache .mypy_cache .coverage htmlcov site/ local_runs/ tmp*.db .tmp_dagster_*/

  docs:
    desc: Start MkDocs development server
    cmds:
      - uv run mkdocs serve

  lint:
    desc: Run ruff linter and formatter checks
    cmds:
      - uv run ruff check .
      - uv run ruff format --check .
      - uv run mypy src --extra-checks

  build:
    desc: Run Podman build and tag the image
    cmds:
      - podman build --platform linux/amd64 -t ghcr.io/arookieds/dagster-code-location-crypto-data:latest -f {{if eq .ENV "LOCAL"}} Dockerfile.local {{else}} Dockerfile {{end}} .

  build-push:
    desc: Run Podman build, tag the image, and push to github
    cmds:
      - task: build
      - podman push ghcr.io/arookieds/dagster-code-location-crypto-data:latest

  rollout-restart:
    desc: Run kubectl rollout restart of the deployment
    cmds:
      - kubectl rollout restart deploy -n dagster --selector=app.kubernetes.io/instance=crypto-data

  run:
    desc: Run Podman run on the built image
    cmds:
      - podman run -d --platform linux/amd64 -p 3000:3000 ghcr.io/arookieds/dagster-code-location-crypto-data:latest

  build-run:
    desc: Run Podman build, tag the image, and runs it
    watch: true
    sources:
      - src/**/*.py
    vars:
      CONTAINER:
        sh: podman ps -q --filter ancestor=ghcr.io/arookieds/dagster-code-location-crypto-data:latest
    cmds:
      - '{{if ne .CONTAINER ""}}podman kill {{.CONTAINER}}; echo Contatiner {{.CONTAINER}} killed!; podman rm {{.CONTAINER}}{{else}}echo "No container to kill!"{{end}}'
      - task: build
      - task: run

  deploy:
    desc: Deploy the code location to the current enabled context
    cmds:
      - kubectl kustomize manifests/ --enable-helm | kubectl apply -f -

  validate:
    desc: Validate Dagster definitions
    cmds:
      - uv run dg check defs

  default:
    desc: Run linting and tests (pre-flight check)
    cmds:
      - task: lint
      - task: test
